MyAnimeList = ["Noblesse", 
"Your lie in april", 
"Re:Zero", 
"Himouto! Umaru-chan", 
"SAO",
"Rent a girlfriend", 
"Yahari Ore no Shieshun Love Come Wa Machigatteiru",
"Assasination Classroom", 
"Tonikaku kawaii", "Steins Gate",
"Kimi to Boku no Saigo no Senjou, Aruiwa , Sekai ga Hajimaru Seisen",
"Gate", 
"Gamers!", 
"Naruto Shippuden", 
"A Silent Voice",
"IS: Infinite Stratos", 
"Tanaka-kun is always listless",
"Gochuumon wa Usagi Desu ka", 
"Darling in the Franxx", "Majo no Tabitabi",
"Seishun Buta Yarou wa Bunny Girl Senpai no Yume ", 
"Tokyo Ghoul",
"Bleach", 
"One Piece",
"Kemistu no Yaiba", "Blend S",
"Astra lost in space", 
"Date a live", 
"FullMetal Alchemist",
"Akame Ga Kill!", 
"Dororo", 
"Demon slayer", 
"Toradora", 
"Inauyasha",
"Soul Eater", 
"Highschool of the dead", 
"Prison school",
"Promise neverland", 
"The God of Highschool", 
"One Punch Man",
"My Hero Academia",
"Haikyu!!!", 
"Attack on Titan", 
"Seven Deadly sins",
"Death Note", 
"Cells at work", 
"Free Eternal summer", 
"Yuwamoshi pedal",
"beyblade series ",
"Gundam! ", 
"Ghost fighter ",
"Dragon ball ",
"Yu Gi Oh! ", 
"Digimon ", 
"Little Battlers Experience", 
"Vangaurd",
"Hyouka", 
"Talentless ", 
"Gakuen Babysitters",
"Cautious Hero: The Hero is Overpowerd but Overly Cautious",
"Bofuri: I Don't Want to Get Hurt, so I'll Max Out My Defense",
"Kuma Kuma Kuma Bear", 
"No Game no Life",
"That Time I Got Reincarnated as a Slime", 
"BanG Dream!",
"Lapis Re:Lights", 
"Servamp", 
"Rail Romanesque",
"Kenichi: The Mightiest Disciple OVA",
"Welcome to Demon School! Iruma-kun",
"If it's for My Daughter, I'd Even Defeat a Demon Lord",
"A Certain Magical Index III", 
"The Ryou's Work Never is Done",
"Goblin Slayer", 
"Monster Girl Doctor", 
"By the Grace of the Gods",
"Konosuba!",
"Blood Lad",
"Gleipnir", 
"Higurashi: When They Cry Gou",
"Endro~", 
"Tari-tari", 
"Bezelbub", 
"Angel beats",
"Sleepy Princess in the demon castle", 
"Black clover", "Horimiya",
"Jaku-Chara Tomozaki-kun",
"The Aristocrat's Otherworldly Adventures: Serving Gods Who Go Too Far",
"Suppose a Kid from the last Dungeon Boonies moved to a  starter town",
"The Hidden Dungeon Only I can enter", "Dr. Stone",
"So I'm a spider? So what?",
"We never learn", 
"Danmachi",
"My Sweet Tryant", 
"Eromanga Sensei", 
"Loving Yamada-kun at lv999!", 
"The Dangers in My Heart", 
"Mahsle: Magic and Muscles", 
"Hell's Paradise", 
"The Legendary Hero is Dead!", 
"Summoned to Another World for a Second Time", 
"KamiKatsu: Working for a God in a Godless World", 
"Tomo-chan is a Girl!", 
"In/Spectre", 
"Oshi no Ko", 
"Don't Toy with Me, Miss Nagatoro", 
"Chillin in my 30s After Getting Fired from the Demon King's Army", 
"Clean Freak Aoyama-kun", 
"Saving 80,000 Gold in Another World for my Retirement", 
"Shikimori's Not Just a Cutie", 
"Spy X Family", 
"Classroom of the Elite", 
"My Dress-Up Darling",
"The Eminence in Shadow",
"Buddy Daddies",
"Wise Man's Grandchild",
"Isekai Cheat Magician",
"My Life as Inukai-san's Dog",
"Dogs and Scissors",
"Soul Land",
"Ao Ashi",
"Tamako Market",
"Tamako Love Story",
"The Tale of Outcasts",
"Komi-san wa, Comyushou desu",
"The Angels Next Door Spoils Me Rotten",
"I Got a CHEAT SKILL in ANOTHER WORLD and Became UNRIVALED in the REAL WORLD, Too",
"High School Prodigies Have It Easy Even in Another World!",
"Black Summoner",
"Skeleton Knight in Another World",
"Parallel World Pharmacy",
"Beast Tamer",
"Ningen Fushin: Adventurers Who Don't Believe in Humanity Will Save the World",
"Campfire Cooking in Another World with My Absurd Skill",
"Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
"Suki na Ko ga Megane wo Wasureta",
"The Duke of Death and His Maid",
"Am actually the strongest?",
"Undead girl murder farce",
"Dark Gathering",
"Meiruko-chan",
"Eiyuu kyoushitsu",
"Level 1 dakedo Unique Skill de Saikyou desu",
"Dekiru Neko wa Kyou mo Yuuutsu",
"Higeki no Genkyou to Naru Saikyou Gedou Last Boss Joou wa Tami no Tame ni Tsukushimasu."

]

    
